targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
]

[advisories]
yanked = "deny"
unsound = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"

skip = [
    # this is only a dev dependency (between nix and rustix)
    { name = "bitflags", version = "1.3.2" },
    { name = "bitflags", version = "2.3.3" },
]

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-DFS-2016"]
copyleft = "deny"
